// src/game/flavorBank.ts
export const FLAVOR_BANK: Record<string, string[]> = {
  pact_signed: [
    "Esteemed diplomats from {actor} and {partner} met at {actorCapital} to discuss the many ways they are both different and the same. In the end, they shook hands and agreed there should be peace.",
    "The {actorLeaderTitle} of {actor} traveled {distance} to personally meet the {partnerLeaderTitle} of {partner}. By dawn the {pactType} bore both signatures.",
    "Wreaths were laid in the great hall of {actorCapital} as {actor} and {partner} ratified the {pactType}. The signing concluded a months-long shuttle diplomacy run by both delegations.",
    "{actor} and {partner} announced a {pactType} this cycle, ending a long silence between {actorCapital} and {partnerCapital}.",
    "After {distance} of courier traffic, envoys from {actor} and {partner} put their names to the {pactType}. Observers called it the most consequential accord of the season.",
    "The {pactType} between {actor} and {partner} was sealed in a closed session at {partnerCapital}. Neither delegation took questions afterward.",
    "Flags of {actor} and {partner} flew side by side over {actorCapital} as the {pactType} took effect. Analysts had predicted the talks would collapse; instead they held.",
    "{partner} accepted the terms tabled by {actor}, and the {pactType} entered the record. The two capitals, long wary of one another, now share a signature.",
    "A delegation from {partner} crossed {distance} to {actorCapital}, where the {pactType} was signed before assembled press. The {actorLeaderTitle} called it the beginning of a working trust.",
    "The {pactType} binding {actor} and {partner} was ratified after weeks of procedural wrangling. Both governments framed it as pragmatism rather than friendship.",
  ],
  pact_broken: [
    "{actor} formally withdrew from its accord with {partner} this cycle. The notice arrived at {partnerCapital} without explanation.",
    "The {actorLeaderTitle} of {actor} tore up the pact with {partner} in a televised address from {actorCapital}. Markets between the two capitals fell within the hour.",
    "Years of treaty between {actor} and {partner} ended quietly, struck from the record at {actorCapital}. No replacement was offered.",
    "{actor} renounced the {pactType} it once signed with {partner}. Diplomats on both sides declined to characterize what comes next.",
    "Word reached {partnerCapital} that {actor} no longer considers itself bound to {partner}. The {partnerLeaderTitle} convened an emergency session.",
    "The accord between {actor} and {partner} is dead. {actor}'s envoys left {partnerCapital} before the ink on the dissolution had dried.",
    "{actor} broke the {pactType} with {partner}, citing irreconcilable interests. The break had been rumored for cycles; its timing still surprised.",
    "A terse communiqué from {actor} dissolved its standing with {partner}. The {distance} between their capitals suddenly felt longer.",
    "{partner} learned of the rupture by dispatch: {actor} has voided the pact between them. Recriminations followed within the day.",
    "The treaty hall at {actorCapital} stood empty as {actor} let its pact with {partner} lapse. Neither side moved to renew.",
  ],
  ship_destroyed: [
    "{partner}'s {shipClass} {shipName} goes silent above {body}. {hpLost} structure burned through before the comms cut. {actor} claims the kill.",
    "Kill confirmed at {tick}: {shipName}, {partner} {shipClass}, breaks up over {body}. No survivors logged.",
    "{actor} guns open up. {shipName} takes {hpLost} and folds. {partner} loses a {shipClass} in {body} orbit.",
    "The {shipClass} {shipName} stops transmitting at {tick}. Debris field spreading over {body}. {actor} on the trigger.",
    "{partner} flag goes dark on {shipName}. {hpLost} HP gone in under a minute. {actor} owns the wreck now.",
    "Last contact with {shipName} at {tick}, low over {body}. The {partner} {shipClass} is scrap. {actor} reports zero losses.",
    "Hull breach, then nothing. {partner}'s {shipName} dies above {body}, {hpLost} structure spent. {actor} called it clean.",
    "{shipName} burned bright and brief over {body}. {actor} put {hpLost} into the {partner} {shipClass} before it cracked open.",
    "Scratch one {shipClass}. {partner}'s {shipName} is gone, {body} orbit, {tick}. {actor} logs the tally.",
    "{actor} caught {shipName} in the open. The {partner} {shipClass} took {hpLost} and went quiet above {body}.",
  ],
  settlement_destroyed: [
    "{actor} ordnance levels {settlementName} on {body}. {popLost} dead. The {settlementType} stops answering at {tick}.",
    "{partner}'s {settlementName} burns. {actor} confirms the {settlementType} is gone, {body} surface scorched, {popLost} lost.",
    "Strike on {settlementName} at {tick}. {actor} hit the {settlementType} hard. {partner} counts {popLost} dead in the rubble.",
    "The lights of {settlementName} go out over {body}. {actor} did this. {popLost} never made it to the shelters.",
    "{settlementName} is rubble. {actor} broke the {settlementType} in one pass; {partner} lost {popLost} and the ground beneath them.",
    "{partner}'s hold on {body} ends with {settlementName}. {actor} reports the {settlementType} destroyed, {popLost} dead, at {tick}.",
    "Fire, then silence. {settlementName} falls to {actor}. {popLost} gone. {partner} has no {settlementType} on {body} now.",
    "{actor} razed {settlementName} at {tick}. The {settlementType} is a crater on {body}. {partner} mourns {popLost}.",
    "{settlementName} took the hit and didn't get up. {actor} confirms {popLost} dead, the {settlementType} dark over {body}.",
    "Whatever {partner} built at {settlementName} is ash. {actor} struck the {settlementType} clean. {popLost} lost on {body}.",
  ],
  ship_damaged: [
    "{partner}'s {shipName} limps off {body} trailing atmosphere. {hpLost} structure gone, but the {shipClass} held. {actor} pressed and broke contact.",
    "Heavy fire over {body}. {actor} laid {hpLost} into {shipName} before the {partner} {shipClass} pulled out.",
    "{shipName} took {hpLost} and lived. The {partner} {shipClass} is venting over {body}, still under power. {actor} did not finish it.",
    "Hull buckled, drives intact. {partner}'s {shipName} survives a mauling above {body}; {hpLost} HP spent. {actor} let it run.",
    "{actor} caught {shipName} clean for {hpLost} damage. The {partner} {shipClass} broke off over {body}, smoking but whole.",
    "{shipName} came home wrong. {hpLost} structure burned away over {body}, but the {partner} {shipClass} made it back from {actor}'s guns.",
    "Contact over {body}: {actor} bloodied {shipName} for {hpLost} before the {partner} {shipClass} slipped the engagement.",
    "{partner}'s {shipName} is hurt. {hpLost} HP off the board after a brush with {actor} above {body}. Repairs pending.",
    "The {shipClass} {shipName} took {actor} fire over {body} and kept flying. {hpLost} structure lost; crew reports the hull will hold.",
    "{actor} opened up over {body}. {shipName} absorbed {hpLost} and disengaged. The {partner} {shipClass} will fight another cycle.",
  ],
  ship_built: [
    "Yards on {body} rolled out the {shipName}, a {shipClass}, for {actor}.",
    "{actor} commissioned the {shipClass} {shipName} this cycle. Trials over {body} reported nominal.",
    "New hull off the line at {body}: the {shipName}, {shipClass}, flying {actor} colors.",
    "{actor}'s shipwrights finished the {shipName}. The {shipClass} entered service in {body} orbit.",
    "The {shipName} cleared final fitting over {body}. {actor} adds one {shipClass} to the order of battle.",
    "{actor} launched the {shipClass} {shipName} from {body}. Acceptance flights begin next cycle.",
    "Slipways at {body} delivered the {shipName} on schedule. {shipClass}, {actor} registry.",
    "One more {shipClass} for {actor}: the {shipName}, built and bonded over {body}.",
    "{actor} took delivery of the {shipName} this cycle. The {shipClass} works up in {body} orbit.",
    "The {shipName} fired its drives for the first time above {body}. {actor}'s newest {shipClass} is operational.",
  ],
  building_completed: [
    "{actor} completed a {building} at {settlementName} on {body}.",
    "The new {building} at {settlementName} came online this cycle. {actor} reports {body} output rising.",
    "Crews on {body} finished the {building} at {settlementName}. {actor} cut the ribbon ahead of schedule.",
    "{settlementName} gains a {building}. {actor}'s engineers signed off after final inspection on {body}.",
    "A {building} now stands at {settlementName}. {actor} expects it to anchor {body} operations for cycles to come.",
    "{actor} brought the {building} at {settlementName} into service. {body} logistics rerouted accordingly.",
    "The {building} at {settlementName} is done. {actor}'s investment in {body} is starting to show.",
    "Construction wrapped on the {building} at {settlementName}, {body}. {actor} moves to staffing.",
    "{actor}'s {building} lit up at {settlementName} this cycle. First throughput logged within the day.",
    "Another structure rises at {settlementName}: a {building}, {actor}-built, {body}-bound.",
  ],
  settlement_founded: [
    "Where there was only regolith, now there is {settlementName}. {actor}'s first colonists raised the dome before the long {body} night could claim them.",
    "On a {bodyType} that had never known a name, {actor} planted {settlementName}. The first beacon answered the dark.",
    "They came {distance} and stopped at {body}, and there they built {settlementName}. {actor} will mark this cycle for generations.",
    "The founders of {settlementName} drove their first stake into {body} this cycle. {actor} calls it a {settlementType}; the colonists call it home.",
    "Before the dust settled, {actor} had walls. {settlementName} stands on {body} now, small against the {bodyType} sky.",
    "{settlementName} began as a single airlock on {body}. By cycle's end {actor} had a {settlementType} drawing breath.",
    "On the cold face of {body}, {actor} lit the lamps of {settlementName}. No one had stood there before.",
    "A {settlementType} where there was nothing: {actor} founded {settlementName} on {body}, and the {bodyType} grew a little less empty.",
    "The charter for {settlementName} was read aloud on {body} as the colonists looked up. {actor} had reached a little further into the system.",
    "{actor}'s flag went up over {settlementName} this cycle. On a {bodyType} like {body}, even a small {settlementType} is an act of faith.",
  ],
  secret_discovered: [
    "Survey crews on {body} uncovered an {secretName}, half-buried in iron-rich dust. Nothing in {actor}'s archives matches the markings.",
    "Something is humming beneath {body}. {actor}'s teams found a {secretName} and have not stopped staring.",
    "On the {bodyType} {body}, {actor} found a {secretName} where the survey said there was nothing. Light caught on metal that should not have been there.",
    "The {secretName} on {body} predates every record {actor} keeps. The crews work in shifts now, unwilling to leave it alone in the dark.",
    "{actor} reports a {secretName} on {body}. The find is intact. The find is old. The find is, by every reading, impossible.",
    "Down in the {bodyType} cold of {body}, {actor}'s surveyors brushed dust from a {secretName}. Then they went very quiet on the comms.",
    "A {secretName}, surfaced from {body}. {actor} has sealed the site and is asking questions it has no words for yet.",
    "The instruments on {body} sang before anyone saw it: a {secretName}, waiting. {actor} claims first contact with whatever this is.",
    "{actor} found a {secretName} on {body}. Carbon and silence and a faint, patient signal nobody can place.",
    "What {actor} pulled from the {bodyType} surface of {body} is a {secretName}, and it changes the map of the possible.",
  ],
  vote_opened: [
    "{actor} brought the motion to {voteTitle} before the Senate this cycle. Debate is open.",
    "The floor recognized {actor}, who tabled a measure to {voteTitle}. Whips on both sides began counting.",
    "A motion to {voteTitle}, sponsored by {actor}, entered the docket. The chamber settled in for a long session.",
    "{actor} called the question: shall the body move to {voteTitle}? The gavel set the clock.",
    "Procedural motion from {actor} — to {voteTitle} — is now before the Senate. Amendments expected.",
    "The {actor} delegation introduced legislation to {voteTitle}. The presiding officer ruled it in order.",
    "Debate opens on {actor}'s motion to {voteTitle}. Galleries are full.",
    "{actor} forced the matter onto the agenda: a vote to {voteTitle}. The chamber will decide before recess.",
    "Read into the record by {actor}: a resolution to {voteTitle}. Committee referral was waived.",
    "The Senate took up {actor}'s proposal to {voteTitle} this cycle. Lobbying continues in the corridors.",
  ],
  vote_resolved: [
    "The motion to {voteTitle} {voteOutcome}. The chamber moved on to the next order of business.",
    "After lengthy debate, the resolution to {voteTitle} {voteOutcome}.",
    "The vote on {voteTitle} {voteOutcome}; the result was entered into the permanent record.",
    "By the close of session, the measure to {voteTitle} {voteOutcome}.",
    "The body has spoken: the motion to {voteTitle} {voteOutcome}. The gavel fell at once.",
    "Tallies are in. The proposal to {voteTitle} {voteOutcome}, and the galleries emptied.",
    "The resolution to {voteTitle} {voteOutcome} after a final round of floor speeches.",
    "On the question to {voteTitle}, the Senate {voteOutcome}. Few were surprised.",
    "The motion to {voteTitle} {voteOutcome}, ending one of the longer debates of the term.",
    "Order restored, the chamber recorded that the measure to {voteTitle} {voteOutcome}.",
  ],
  tech_advanced: [
    "{actor}'s labs pushed {techName} to {techLevel} this cycle. The breakthrough holds under review.",
    "Field trials confirm it: {actor} now operates {techName} at {techLevel}.",
    "{actor} cracked the next threshold in {techName}, reaching {techLevel}. Rivals will be reading the abstract closely.",
    "After cycles of dead ends, {actor}'s {techName} program hit {techLevel}. The team is, by all accounts, insufferable about it.",
    "{techName} advances to {techLevel} under {actor}. The implications are already rippling through doctrine.",
    "{actor} published {techLevel} results in {techName}. Peer factions are scrambling to replicate.",
    "A clean run in the {actor} {techName} lab: {techLevel} achieved, ahead of projection.",
    "{actor} now holds {techLevel} in {techName}. The edge is small, the consequences are not.",
    "Engineers at {actor} logged {techName} {techLevel} this cycle. The notebooks read: it works.",
    "{actor} closed the gap in {techName}, posting {techLevel}. Quietly, then all at once.",
  ],
  trade_accepted: [
    "{actor} exchanged {resourceTraded} with {partner} this cycle. Markets shrugged.",
    "Deal closed: {actor} and {partner} settled on {resourceTraded}. Both sides called it fair.",
    "{partner} took {actor}'s offer of {resourceTraded}. The exchange cleared by close of business.",
    "{actor} and {partner} agreed terms — {resourceTraded} — and the ledgers balanced.",
    "Trade confirmed between {actor} and {partner}: {resourceTraded}. Volume up, spreads tight.",
    "{actor} moved {resourceTraded} to {partner} this cycle. Analysts noted the relationship warming.",
    "Hands shaken on {resourceTraded}. {actor} and {partner} kept the channel open another cycle.",
    "The {resourceTraded} swap between {actor} and {partner} went through without a hitch. Routine, profitable, done.",
    "{partner} signed for {actor}'s {resourceTraded}. Neither side overpaid; both walked away satisfied.",
    "{actor} and {partner} booked {resourceTraded}. A small deal, but the corridor between them stays busy.",
  ],
  trade_declined: [
    "{partner} passed on {actor}'s offer of {resourceTraded}. Talks ended cordially, and unfinished.",
    "{actor} tabled {resourceTraded}; {partner} declined. The market read it as posturing.",
    "No deal. {partner} rejected {actor}'s {resourceTraded}, and the books stayed where they were.",
    "{actor} and {partner} could not agree on {resourceTraded}. Both sides cited price, neither said more.",
    "{partner} walked from {actor}'s {resourceTraded} proposal. Analysts saw leverage, not anger.",
    "The {resourceTraded} offer from {actor} died on {partner}'s desk. The channel stays open; the deal does not.",
    "{partner} returned {actor}'s {resourceTraded} terms unsigned. A counteroffer is rumored but unconfirmed.",
    "{actor} couldn't move {partner} on {resourceTraded}. The two sides booked nothing and blamed nobody.",
    "Negotiations over {resourceTraded} stalled out. {partner} declined {actor}, and the floor went quiet.",
    "{partner} said no to {resourceTraded}. {actor}'s traders shrugged and started the next cycle's pitch.",
  ],
  asteroid_impact: [
    "{settlementName} fell silent when the rock came down on {body} at {tick}. {actor} launched it; {partner} buried what was left.",
    "An asteroid struck {body} at {tick}. The {partner} settlement at {settlementName} went dark. {actor} does not deny the order.",
    "Impact on {body}, {tick}. {settlementName} is gone. The stone that killed it was steered there by {actor}, against {partner}.",
    "{actor} dropped a mountain on {body}. {partner}'s {settlementName} was beneath it. The crater is still glowing.",
    "At {tick}, {body} took a hit it was never built to survive. {settlementName} ceased to exist. {actor} owns the trajectory.",
    "The rock found {body} at {tick}. {partner}'s {settlementName} answered no further calls. {actor}'s fingerprints are on the launch.",
    "{partner} lost {settlementName} when {body} was struck at {tick}. {actor} called it a strike; the survivors called it the end of the world.",
    "Asteroid impact, {body}, {tick}. {settlementName} flattened. {actor} routed the stone across the system to land it on {partner}.",
    "{body} shuddered and broke at {tick}. {settlementName} was already gone. {actor} aimed it; {partner} will count the dead for cycles.",
    "They saw it coming and could not move it. {actor}'s asteroid took {body} and {settlementName} with it at {tick}, and {partner} was left with the silence.",
  ],
};
