-- Persist the player's custom ship name through the build queue.
--
-- Background: handleQueueBuild accepted body.ship_name per its own
-- docstring but never read it. The completion handler in room.js then
-- generated a default `${shipClass} T${tick}` name, so every custom
-- name typed in BuildPanel silently dropped. Playtester reported
-- "custom names for ships dosnt seem to work".
--
-- Additive-only: nullable column with no default. Existing queued
-- rows stay NULL and fall through to the legacy default name at
-- completion time.
ALTER TABLE game_body_build_queue ADD COLUMN ship_name TEXT;
