-- ============================================================
-- RENUMBERED FROM 0115. It collided with 0115_abandoned_structures,
-- which is the failure this project has been bitten by before — a
-- duplicate 0089 once took production down. The applier keys on the
-- FILENAME rather than the number, so the collision does not stop it
-- outright; it just leaves two migrations racing for the same slot in a
-- sorted list, and on staging the abandoned-structures column ended up
-- missing while three files queried it, including a tick pass.
--
-- migrationNumbering.test.ts now fails on any duplicate, which is the
-- part that should have existed before either of us needed it.
--
-- Let the builder choose the silhouette.
--
-- Ships have had this since the icon expansion: nineteen variants per
-- class and a picker at construction. Megastructures had exactly one
-- look each, procedurally drawn, and every gate in every game was the
-- same gate.
--
-- Three per kind rather than nineteen. A structure is a landmark you
-- build a handful of, not a hull you stamp out by the dozen, and three
-- distinct silhouettes is the difference between "my gate" and "a gate"
-- without asking anyone to author sixty sprites.
--
-- NULL means "whoever built this chose nothing" and renders as A, so
-- every structure already standing keeps a valid look.
-- ============================================================

ALTER TABLE game_megastructures ADD COLUMN variant TEXT;
