// ============================================================
// CaptainAvatar — imported portrait images, SVG bust as fallback.
//
// The 12 SVG busts below were always placeholders ("Lorne is authoring
// final art; the contract is 'render avatar id N at size S'"). That
// contract is unchanged — this just satisfies it with real faces from
// public/portraits, generated by scripts/import-portraits.js.
//
// The SVG is KEPT, not deleted, and does real work: it renders while an
// image is still loading and permanently for any id that has no file, so
// a missing or failed portrait degrades to the old bust instead of an
// empty box. It is also the whole avatar system in single-player, which
// ships no portrait files.
//
// ORIGINAL NOTES (still true of the fallback):
// code-shipped SVG portraits (DESIGN-captains §4).
// 12 generic busts built from a shared frame with per-id variation
// (helmet shape, visor, skin/suit tones). No uploads (cost +
// moderation surface); faction-tintable via `tint`. Placeholder
// quality by design — Lorne is authoring final art; the contract is
// "render avatar id N at size S".
// ============================================================

import React, { useState } from 'react';

interface Props {
  avatarId?: string | null;
  size?: number;
  /** Faction accent for the suit collar. Defaults to neutral steel. */
  tint?: string;
}

// Per-id palette + geometry knobs. Index = a1..a12.
const VARIANTS: Record<string, { skin: string; suit: string; visor: boolean; hair: string; dome: boolean }> = {
  a1:  { skin: '#d9a066', suit: '#3a4a5a', visor: false, hair: '#2b2b2b', dome: false },
  a2:  { skin: '#8d5524', suit: '#44405e', visor: false, hair: '#101010', dome: false },
  a3:  { skin: '#f1c27d', suit: '#3f5747', visor: false, hair: '#7a4b21', dome: false },
  a4:  { skin: '#c68642', suit: '#5a3a3a', visor: false, hair: '#3a2a18', dome: false },
  a5:  { skin: '#ffdbac', suit: '#37474f', visor: false, hair: '#b0b0b0', dome: false },
  a6:  { skin: '#a1665e', suit: '#4a3a5a', visor: false, hair: '#1a1a2a', dome: false },
  a7:  { skin: '#d9a066', suit: '#2f4550', visor: true,  hair: '#2b2b2b', dome: true  },
  a8:  { skin: '#8d5524', suit: '#4f3a2a', visor: true,  hair: '#101010', dome: true  },
  a9:  { skin: '#f1c27d', suit: '#3a3a3a', visor: true,  hair: '#5a3a1a', dome: true  },
  a10: { skin: '#c68642', suit: '#2a4a4a', visor: true,  hair: '#2a1a0a', dome: true  },
  a11: { skin: '#ffdbac', suit: '#5a4a2a', visor: true,  hair: '#e0e0e0', dome: true  },
  a12: { skin: '#a1665e', suit: '#3a2f45', visor: true,  hair: '#0a0a1a', dome: true  },
};

/**
 * Which portrait file an avatar id maps to.
 *
 * Legacy ids matter: every captain already alive in a live game carries
 * a1-a12 from the placeholder era. Mapping a{n} -> p{n} means they all
 * pick up a real face on this deploy instead of sitting on the old bust
 * until someone thinks to cycle them.
 */
function portraitFile(avatarId: string | null | undefined): string | null {
  const id = (avatarId ?? '').trim();
  if (/^p\d+$/.test(id)) return `${process.env.PUBLIC_URL ?? ''}/portraits/${id}.webp`;
  const legacy = /^a(\d+)$/.exec(id);
  if (legacy) return `${process.env.PUBLIC_URL ?? ''}/portraits/p${legacy[1]}.webp`;
  return null;
}

export const CaptainAvatar: React.FC<Props> = ({ avatarId, size = 24, tint = '#4ecdc4' }) => {
  const v = VARIANTS[avatarId ?? ''] ?? VARIANTS.a1;
  const src = portraitFile(avatarId);
  // One flag, not a loading state: the SVG is already the thing we want
  // on screen until the image is good, so there is nothing to spin.
  const [failed, setFailed] = useState(false);

  if (src && !failed) {
    return (
      <img
        src={src}
        alt=""
        aria-hidden
        width={size}
        height={size}
        loading="lazy"
        decoding="async"
        onError={() => setFailed(true)}
        style={{
          width: size, height: size,
          borderRadius: 4,
          // Faces are cropped square at import, so cover only ever trims
          // rounding error — it is here so a non-square drop-in cannot
          // stretch a face.
          objectFit: 'cover',
          background: '#0d1420',
          // Faction accent kept from the SVG treatment, so a portrait
          // still reads as belonging to someone.
          border: `1px solid ${tint}`,
          flexShrink: 0,
          display: 'block',
        }}
      />
    );
  }

  return (
    <svg
      width={size} height={size} viewBox="0 0 32 32" aria-hidden
      style={{ borderRadius: 4, background: '#0d1420', border: '1px solid #22303f', flexShrink: 0 }}
    >
      {/* suit shoulders */}
      <path d="M4 32 Q4 22 16 22 Q28 22 28 32 Z" fill={v.suit} />
      {/* collar accent in faction tint */}
      <path d="M9 32 Q9 25 16 25 Q23 25 23 32 Z" fill="none" stroke={tint} strokeWidth={1.4} />
      {/* head */}
      <circle cx={16} cy={13} r={7} fill={v.skin} />
      {/* hair / helmet dome */}
      {v.dome
        ? <path d="M8 13 a8 8 0 0 1 16 0 l-1.5 0 a6.5 6.5 0 0 0 -13 0 Z" fill={v.suit} />
        : <path d="M9.2 11 a7 7 0 0 1 13.6 0 q-3 -3.4 -6.8 -3.4 q-3.8 0 -6.8 3.4 Z" fill={v.hair} />}
      {/* visor or eyes */}
      {v.visor
        ? <rect x={10.5} y={11} width={11} height={4.4} rx={2.2} fill="#0a0e14" opacity={0.85} />
        : (
          <>
            <circle cx={13.2} cy={13} r={1} fill="#0a0e14" />
            <circle cx={18.8} cy={13} r={1} fill="#0a0e14" />
          </>
        )}
    </svg>
  );
};
