// =====================================================================
// GENERATE worker/generated/shipIconSvgs.js FROM THE REAL COMPONENT.
//
// The battle widget draws ships on a PNG, in the Worker, where there is
// no DOM and no React. It must still draw THE icon -- the one the game
// shows in the situation log, livery shading, engine glow and all -- and
// not a hand-copied approximation of it. So this renders every icon the
// game can show through ShipIcons.tsx itself, with react-dom/server, and
// writes out the exact markup it produced. The Worker rasterises that
// markup; it never reinterprets it.
//
// WHY PER HEALTH COLOUR and not one template: IconFrame derives the
// keel shade and dorsal highlight from the primary colour in JS
// (darken/lighten), so the SVG for a green hull is not the SVG for a red
// hull with the colour swapped. Rendering each colour the widget uses is
// the only way to get the component's own answer for it.
//
// RERUN THIS WHENEVER ShipIcons.tsx CHANGES:
//   npx esbuild scripts/gen-ship-icon-svgs.tsx --bundle --platform=node \
//     --format=esm --outfile=scripts/.gen-ship-icons.mjs --jsx=automatic \
//     && node scripts/.gen-ship-icons.mjs
// sim/battleWidget.mjs checks the output covers every class and variant,
// so a new variant that nobody regenerated for fails there rather than
// drawing nothing on somebody's home screen.
// =====================================================================

import { renderToStaticMarkup } from 'react-dom/server';
import { writeFileSync, mkdirSync } from 'node:fs';
import { ShipIcon, DEFAULT_SHIP_ICONS, iconClassFor } from '../src/components/ShipIcons';

// The situation log hull ramp, EXACTLY (SituationLog.tsx hpColor and
// hpColor2). The icon is only the real icon if it is painted the way the
// game paints it.
const BUCKETS = {
  green: { color: '#6ee7b7', color2: '#3f8f78' },
  amber: { color: '#ffb84d', color2: '#a67430' },
  red: { color: '#ff5e5e', color2: '#a63636' },
  unknown: { color: '#8aa0b4', color2: '#5a7080' },
} as const;

const CLASSES = ['corvette', 'frigate', 'destroyer', 'freighter', 'colony'] as const;
const VARIANTS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L',
  'M', 'N', 'O', 'P', 'Q', 'R', 'S'] as const;

// Rendered at a nominal size; the Worker rasterises at whatever size the
// card needs, and SVG scales exactly, so this number only sets the
// width/height attributes the rasteriser then overrides.
const NOMINAL = 32;

const out: Record<string, string> = {};
let n = 0;
for (const cls of CLASSES) {
  for (const v of VARIANTS) {
    for (const [bucket, c] of Object.entries(BUCKETS)) {
      const svg = renderToStaticMarkup(
        <ShipIcon shipClass={cls} variant={v} size={NOMINAL} color={c.color} color2={c.color2} />,
      );
      out[`${cls}:${v}:${bucket}`] = svg;
      n += 1;
    }
  }
}

mkdirSync('worker/generated', { recursive: true });
const body = `// GENERATED by scripts/gen-ship-icon-svgs.tsx from src/components/ShipIcons.tsx.
// DO NOT EDIT BY HAND. Rerun the generator when the icons change.
//
// Key: "<class>:<variant>:<health bucket>". Value: the exact SVG markup
// ShipIcon renders for that class, variant and hull-health colour.
export const SHIP_ICON_SVGS = ${JSON.stringify(out)};

// The class a ship draws as, and the variant it draws with when the
// player never chose one -- both read out of ShipIcons.tsx, so a card
// can never disagree with the game about what a given ship looks like.
export const DEFAULT_SHIP_ICONS = ${JSON.stringify(DEFAULT_SHIP_ICONS)};
export const ICON_CLASS_FOR = ${JSON.stringify(Object.fromEntries(
  ['corvette', 'frigate', 'destroyer', 'freighter', 'colony', 'mega_destroyer', 'mobile_foundry']
    .map(c => [c, iconClassFor(c)]),
))};
`;
writeFileSync('worker/generated/shipIconSvgs.js', body);
console.log(`wrote ${n} icon SVGs, ${body.length} bytes`);
