// =====================================================================
// GENERATE THE SERVER'S EMBLEM ART FROM THE REAL COMPONENT.
//
// The watch's flags and the widget's territory strip draw faction
// emblems on the server, where there is no DOM and no React. They must
// still be THE emblem the game draws, premium ones included, so this
// renders every emblem (EMBLEM_IDS and PREMIUM_EMBLEM_IDS) through
// FactionEmblem.tsx's own emblemSvgElement with react-dom/server and
// writes two things:
//
//   worker/generated/emblemSvgs.js  the exact SVG, white, which the
//     watch's flag route rasterises at whatever size it is asked for;
//   worker/_emblemMasks.js          24x24 1-bit masks, which the Herald
//     strip (both its renderers) stamps from.
//
// The masks used to be baked by hand in a browser, and the ten premium
// emblems never were: on the watch and the widget they drew as a plain
// dot. resvg (already the server's rasteriser) does the baking now.
//
// RERUN WHENEVER FactionEmblem.tsx OR THE EMBLEM LISTS CHANGE:
//   npx esbuild scripts/gen-emblem-art.tsx --bundle --platform=node \
//     --format=esm --outfile=scripts/.gen-emblem-art.mjs --jsx=automatic \
//     && node scripts/.gen-emblem-art.mjs
// src/render/__tests__/wearArt.test.ts fails if an emblem is missing.
// =====================================================================

import { renderToStaticMarkup } from 'react-dom/server';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { initWasm, Resvg } from '@resvg/resvg-wasm';
import { emblemSvgElement } from '../src/components/FactionEmblem';
import { EMBLEM_IDS, PREMIUM_EMBLEM_IDS } from '../src/game/emblems';

const require = createRequire(import.meta.url);
await initWasm(readFileSync(require.resolve('@resvg/resvg-wasm/index_bg.wasm')));

const MASK = 24;
// The browser bake's threshold, so the free masks keep their shapes.
const ALPHA_ON = 110;

const ids = [...EMBLEM_IDS, ...PREMIUM_EMBLEM_IDS];
const svgs: Record<string, string> = {};
const masks: Record<string, string> = {};
for (const id of ids) {
  const svg = renderToStaticMarkup(emblemSvgElement(id, 96, '#ffffff'));
  svgs[id] = svg;
  const img = new Resvg(svg, { fitTo: { mode: 'width', value: MASK } }).render();
  const px = img.pixels;
  const bytes: number[] = [];
  let cur = 0, n = 0;
  for (let i = 0; i < MASK * MASK; i++) {
    cur = (cur << 1) | (px[i * 4 + 3] > ALPHA_ON ? 1 : 0); n++;
    if (n === 8) { bytes.push(cur); cur = 0; n = 0; }
  }
  if (n) { cur <<= (8 - n); bytes.push(cur); }
  masks[id] = Buffer.from(bytes).toString('base64');
}

mkdirSync('worker/generated', { recursive: true });
writeFileSync('worker/generated/emblemSvgs.js',
  '// GENERATED by scripts/gen-emblem-art.tsx from src/components/FactionEmblem.tsx.\n'
  + '// DO NOT EDIT BY HAND. Rerun the generator when the emblems change.\n'
  + '// Each value is the emblem\'s SVG, white, as the game draws it.\n'
  + `export const EMBLEM_SVGS = ${JSON.stringify(svgs, null, 0)};\n`);

// Keep the masks file's header and helper; replace only the table.
const MF = 'worker/_emblemMasks.js';
const prev = readFileSync(MF, 'utf8').replace(/\r\n/g, '\n');
const start = prev.indexOf('export const EMBLEM_MASKS = {');
const end = prev.indexOf('\n};\n', start) + 4;
const table = 'export const EMBLEM_MASKS = {\n'
  + Object.entries(masks).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `  ${k}: '${v}',`).join('\n')
  + '\n};\n';
writeFileSync(MF, prev.slice(0, start) + table + prev.slice(end));
console.log(`emblems: ${ids.length} (${PREMIUM_EMBLEM_IDS.length} premium) -> emblemSvgs.js, _emblemMasks.js`);
