// AUTO-GENERATED by scripts/bundle-migrations.js. Do not edit by hand.
<<<<<<< HEAD
export const GIT_SHA = "1732e9968def704ab8fdf2f5d3661ad79dd63ebe";
export const BUILT_AT = "2026-08-16T19:11:20.381Z";
=======
export const GIT_SHA = "f1e15b218651a99018ac4188e1c3d683a91c1d4c";
export const BUILT_AT = "2026-08-16T19:14:53.523Z";
>>>>>>> 5b7237a (Analytics: surface transit combat, which nothing was reading)
